name: Sphinx Build Documentation

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3.10-venv python3.10-dev
    
    - uses: actions/checkout@v3

    - name: Prepare venv and install project
      run: |
        python3.10 -m venv venv
        source venv/bin/activate
        pip install poetry
        poetry install
        pip install sphinx
    
    - name: Build api-doc
      run: |
        sphinx-apidoc -o docs src/metrics_as_scores "**/webapp/*" --force
        sphinx-build docs/ docs/_build

    - name: Commit documentation changes
      run: |
        mkdir gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
