name: Sphinx Build Documentation

on:
  push:
    branches:
      - 'master'


jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3.10-venv python3.10-dev
      
      - uses: actions/checkout@v3

      - name: Prepare venv and install project
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          pip install poetry
          poetry install
          poetry add sphinxcontrib-apidoc sphinx-autoapi
      
      - name: Build api-doc
        run: |
          sphinx-apidoc -o docs src/metrics_as_scores "**/webapp/*" --force
          sphinx-build docs/ docs/_build
      
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      
      # Publish built docs to gh-pages branch.
      - name: Commit documentation changes
        run: |
          git clone https://github.com/MrShoenel/metrics-as-scores.git --branch gh-pages --single-branch temp
          cp -rf docs/_build/html/* temp/docs/
          cd temp/docs
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: temp/docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
